### ISSUE TITLE
wp_home

### ISSUE THREAD

**Issue by aslakr** [thedigitalembassy/adeptus#1]
I suppose this isn't correct:

    Notice: Use of undefined constant WP_HOME - assumed 'WP_HOME' in /[…]/wp-content/plugins/adeptus-activity-audit-log/src/AlertManager.php on line 27

https://github.com/thedigitalembassy/adeptus/blob/2fb05017b68c7e166fc4d9b6758b04a98c0a0c07/src/AlertManager.php#L27-L28

What should be the difference between `wp_home` and `domain`?

**Comment by killgallic** [comment]
Hi @aslakr  

The WP_HOME constant should be set to http://your-domainname.com, I have merged in your pull request as to avoid notices like these. 

Thank you for contributing to Adeptus!
